# Generated by Django 5.1.2 on 2024-10-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
